apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommendation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-recommendation
  template:
    metadata:
      labels:
        app: movie-recommendation
    spec:
      containers:
      - name: movie-recommendation-container
        image: nicodc/movie-recommendation:latest
        ports:
        - containerPort: 8501
